Enable secret

diff --git a/.github/workflows/sm-deploy-bpmn.yaml b/.github/workflows/sm-deploy-bpmn.yaml
--- a/.github/workflows/sm-deploy-bpmn.yaml
+++ b/.github/workflows/sm-deploy-bpmn.yaml
@@ -42,29 +42,35 @@ jobs:
           ls -al ${{ github.workspace }}/${{ matrix.file }}
 
 # cluster with Identity + Client Secret/ClientID
-#      - name: Get Bearer Token
-#        id: get-bearer-token
-#        run: |
-#          token=$(curl -s ""${{ secrets.OAUTH_TOKEN_URL }}"" --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode "client_id=${{ secrets.ZEEBE_CLIENT_ID}}" --data-urlencode "client_secret=${{ secrets.ZEEBE_CLIENT_SECRET }}" --data-urlencode 'audience=zeebe.camunda.io' | jq -r '.access_token')
-#          echo $token
-#          echo "token=$token" >> $GITHUB_OUTPUT
-
-#      - name: Deploy to Zeebe
-#        id: deploy-to-zeebe
-#        run: |
-#          response=$(curl -s -X POST "${{ secrets.ZEEBE_URL }}/v2/deployments" -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.token }}" -F "resources=@${{ github.workspace }}/${{ matrix.file }}")
-#          echo "$response"
-#          echo "response=$response" >> $GITHUB_OUTPUT
-
- # Cluster with no Identity or no ClientSecret/ClientID
-      - name: Deploy to Zeebe
+      - name: Get Bearer Token
+        id: get-bearer-token
         run: |
-          echo "Server:" ${{secrets.ZEEBE_REST_ADDRESS}} | sed 's/./& /g' 
-          STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST "${{ secrets.ZEEBE_REST_ADDRESS }}/v2/deployments" -F "resources=@${{ github.workspace }}/${{ matrix.file }}")
-          echo "HTTP Status: $STATUS"
-          
-          if [[ "$STATUS" -ge 400 ]]; then
-            echo "❌ API call failed with status $STATUS"
-            cat response.txt
-            exit 1
-          fi
+          token=$(curl -s ""${{ secrets.OAUTH_TOKEN_URL }}"" --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode "client_id=${{ secrets.ZEEBE_CLIENT_ID}}" --data-urlencode "client_secret=${{ secrets.ZEEBE_CLIENT_SECRET }}" --data-urlencode 'audience=zeebe.camunda.io' | jq -r '.access_token')
+          echo $token
+          echo "token=$token" >> $GITHUB_OUTPUT
+
+      - name: Deploy to Zeebe
+        id: deploy-to-zeebe
+        run: |
+               echo "Server:" ${{secrets.ZEEBE_REST_ADDRESS}} | sed 's/./& /g' 
+               STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST "${{ secrets.ZEEBE_REST_ADDRESS }}/v2/deployments" -F "resources=@${{ github.workspace }}/${{ matrix.file }}")
+               echo "HTTP Status: $STATUS"
+               
+               if [[ "$STATUS" -ge 400 ]]; then
+               echo "❌ API call failed with status $STATUS"
+               cat response.txt
+               exit 1
+               fi
+
+# Cluster with no Identity or no ClientSecret/ClientID
+#      - name: Deploy to Zeebe
+#        run: |
+#          echo "Server:" ${{secrets.ZEEBE_REST_ADDRESS}} | sed 's/./& /g'
+#          STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST "${{ secrets.ZEEBE_REST_ADDRESS }}/v2/deployments" -F "resources=@${{ github.workspace }}/${{ matrix.file }}")
+#          echo "HTTP Status: $STATUS"
+#
+#          if [[ "$STATUS" -ge 400 ]]; then
+#            echo "❌ API call failed with status $STATUS"
+#            cat response.txt
+#            exit 1
+#          fi
